apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sample-webhook-config
webhooks:
  - name: sample-webhook-server.example.com
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 1
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        namespace: "webhook"
        name: "sample-webhook-server"
        path: "/validate-pods"
      caBundle: <TBA>
