apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    webhook-validate: "true"
    webhook-mutate: "false"
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent